### PR TITLE
Suggestion for issue #305

### PR DESCRIPTION
**Pull request by mammo0**
This PR is a suggestion for fixing issue #305 that was opened by me some time ago.

I've tested it on some of my Kodi installations and it seems that now my Emby server is not running into memory issues.
The plugin also doesn't fail with a timeout error anymore.

For achieving that I used the already implemented `get_items` method of `resources/lib/downloader.py`. As additional query parameter I used `MinDateLastSavedForUser`. This parameter is also used in the previous used method `get_date_modified` of `libraries/emby/core/api.py`.

When using the `get_items` method as described above, only chunks with the size of the `limitIndex` setting of the plugin are fetched from the Emby server.

In my second commit I added some progress output for the user. This is usefull if there are a lot of changes that are fetched from the server.

Please let me know your thoughts on this. Thank you.

### CODE REVIEW

**Comment by angelblue05** [comment]
Hey thanks for that! I’ll ping @sualfred to have a look.

**Comment by sualfred** [comment]
Aye, I'll take a look at it tomorrow

**Comment by angelblue05** [comment]
Thanks, merged. Sorry I couldn't get to it sooner. I'll make a beta build very soon.

**Comment by mammo0** [comment]
Hello @hoffleit,

the argument `dialog` in `def fast_sync(self, plugin, dialog):` should normally be provided by the `@progress()` decorator.
See file `resources/lib/helper/wrapper.py`.

**Comment by hoffleit** [comment]
Well, @mammo0, sounds very reasonable indeed.

Then, there seems to be a problem within the @progress decorator.

I think I'm slowly coming to the point of truth. How about this change. Again, with this change, fast_sync works for me. Haven't look for side effects, though.

```
diff --git a/resources/lib/helper/wrapper.py b/resources/lib/helper/wrapper.py
index bf2f87ae..a5dca314 100644
--- a/resources/lib/helper/wrapper.py
+++ b/resources/lib/helper/wrapper.py
@@ -20,10 +20,15 @@ def progress(message=None):
     ''' Will start and close the progress dialog.
     '''
     def decorator(func):
-        def wrapper(self, item=None, *args, **kwargs):
+        def wrapper(self, *args, **kwargs):
 
             dialog = xbmcgui.DialogProgressBG()
 
+            if "item" in kwargs:
+                item = kwargs["item"]
+            else:
+                item = None
+
             if item and type(item) == dict:
 
                 dialog.create(_('addon_name'), "%s %s" % (_('gathering'), item['Name']))
@@ -32,9 +37,6 @@ def progress(message=None):
                 dialog.create(_('addon_name'), message)
                 LOG.info("Processing %s", message)
 
-            if item:
-                args = (item,) + args
-
             try:
                 result = func(self, dialog=dialog, *args, **kwargs)
                 dialog.close()

```

**Comment by mammo0** [comment]
I'm sorry but I can't reproduce your error, @hoffleit... Tested the current version of the Emby addon on two different Kodi setups.

And I also don't know why your above fix is working and `def wrapper(self, item=None, *args, **kwargs):` doesn't. Because in my opinion what you've added to the code should be done automatically by the Python interpreter.

**Comment by hoffleit** [comment]
I'm getting this error on CoreElec 9.2.0 (Kodi 18.4), which appearently uses Python 2.7.16.

> Starting Kodi (18.4 Git:e95dc442265375aa0cd75284eeaf70ad99b04862). Platform: Linux ARM 32-bit
> Using Release Kodi x32 build
> Kodi compiled 2019-09-15 by GCC 8.3.0 for Linux ARM 32-bit version 3.14.29 (200221)
> Running on CoreELEC (official): 9.2.0, kernel: Linux ARM 64-bit version 3.14.29 aarch64
> FFmpeg version/source: 4.0.4-Kodi
> Host CPU: AArch64 Processor rev 4 (aarch64), 4 cores available
> ARM Features: Neon enabled
> ...
> EMBY.entrypoint.service -> Python Version: 2.7.16 (default, Sep 15 2019, 17:03:58) [GCC 8.3.0]
> ...

Emby for Kodi was v4.1.15.

**Comment by mammo0** [comment]
Well, I don't have a device at home that can run CoreElec. So I can't test this...

I suggest that you open a separate issue for your problem. Maybe a main developer of the Emby Kodi addon can help you.

**Comment by hoffleit** [comment]
@mammo0, ok, I'll open a new issue. But on which two Kodi setups (Kodi version, Python version, platform) did you test this successfully? It smells like a Python thing to me at the moment.

**Comment by mammo0** [comment]
First setup is a RPi 3B with Libreelec 9.0.2 (Kodi 18.2).
And the second is Kodi 18.4 on Arch Linux.
Right now I don't have access to the log files, so I can't provide the used Python version.

**Comment by hoffleit** [comment]
I opened a separate issue for the problem with fast_sync arguments: #302 

@angelblue05 fixed the issue: `self.fast_sync(plugin=enable_fast_sync)`

**Comment by mammo0** [comment]
@hoffleit glad to here that a solution was found :)

**Pull request merged**
