### PR TITLE
Revert "Faster XML processing and lower memory"

### PR DESCRIPTION
**Pull request by kravone**
Reverts MediaBrowser/plugin.video.emby#44

This commit causes library sync thread error on libreelec see:http://sprunge.us/dJcG

Reverting fixed it...but probably needs some investigation as to why its causing it

### CODE REVIEW

**Comment by angelblue05** [comment]
Thanks for verifying this - it's been reverted.

**Comment by kravone** [comment]
jesus christ that was fast...

**Comment by angelblue05** [comment]
I will review it at a later time

**Comment by im85288** [comment]
Wow instant merging! How about for users not using libreelc?

**Comment by angelblue05** [comment]
It wasn't broken to begin with, but I will re-implement the change if it's fixable, once I review it. Anything to do with xml is unpredictable, especially cross platform. There's a lot of functions that work differently and/or are not available. If it's not able to replicate the same xml as Kodi, then it should be left as is, don't you agree?

**Comment by im85288** [comment]
Yes for sure, my point really was the original PR must have worked for the OP but fully agree testing on more platforms is needed. Possibly if it's only openelec/libreelec they can be excluded so that other platforms could gain from the potential performance increase. All hypothetical though :)

**Comment by SpootDev** [comment]
Looking at the log I'm confused how this blows up.  Looks like a valid dict and people use celement for those quite often.  Bashing my head on desk.

**Comment by im85288** [comment]
Yeah looks like one of those errors that's been around for a while: http://pythonquirks.blogspot.co.uk/2010/03/more-elementtree-annoyances.html

Maybe it's only Linux having the problems..pita

**Comment by faush01** [comment]
Why do we need faster XML?

**Comment by angelblue05** [comment]
We don't - honestly, everything is written once and left alone. It's very rare we'll rewrite xmls...

**Comment by faush01** [comment]
I think very early on with the very first version (a long time ago) when it was just me and xnappo we were using XML from the server instead of JSON and had a few problems getting XML to work uniformly on all systems. In the end once we switched to JSON we dropped back to using the none native XML parser as it seemed to give a better more stable more uniform result across all platforms.

Now we are not using XML as a main data format for transferring actual lib data and just use ti to save some Kodi related config files I don think we need to worry about speed at all and in that case I would say stick with the one that was know to work.

**Comment by SpootDev** [comment]
Ha, what can I say.  I'm old-school (just missed punch cards) and old!  I'll do almost anything to save cpu cycles.  :)

Since this is indeed a low-volume call I'm not gunna mess with it anymore.  It just reinforces my hatred for the python xml libs.  So glad I picked json for my apps as it doesn't make me want to punch a box of kittens.

**Pull request merged**
