### PR TITLE
get kodi_id from kodi database

### PR DESCRIPTION
**Pull request by agentxan**
If kodi_id is not supplied then retrieve the kodi_id of the current file from the kodi database

### CODE REVIEW

**Comment by marcelveldt** [comment]
What's the use case for this? There's a much easier method to get the Kodi Id.

**Comment by agentxan** [comment]
It is for when kodi does not report the item id or media type when played from the home screen widgets, like the recently played widget on kodi 17.  I really do not know that much about python so there may be better ways to get the id. This was just the way that I saw the plex addon solve the problem and added in in so that my machines would work.
https://emby.media/community/index.php?/topic/44807-krypton-not-reporting-play-status-to-server/

**Comment by chrisnappi** [comment]
marcel - can you please review the issue and this request?  this is a long standing issue and this solution works - we just may already have some 'helper' routines that could make it cleaner - but I don't really know the db code very well.

**Comment by xnappo** [comment]
Above comment is me btw :)  Signed in to my work account.

**Comment by marcelveldt** [comment]
sorry, will do so later this week.

**Comment by marcelveldt** [comment]
OK, this is actually a bug in kodi Krypton. The database id is not set when playback was started from a widget. This should be fixed with Kodi 17.1 so we should test that first

**Comment by agentxan** [comment]
I just installed 17.1 on my windows machine and tested playing a tv episode from the widgets. 
I still get the following errors.

17:33:55.344 T:282148  NOTICE: EMBY.kodimonitor -> Method: Player.OnPlay Data: {"item":{"title":"","type":"movie"},"player":{"playerid":1,"speed":1}}
17:33:55.344 T:282148  NOTICE: EMBY.kodimonitor -> Item is invalid for playstate update

17:33:59.750 T:282148  NOTICE: EMBY.player -> Could not find itemId, cancelling playback report...

The log is at http://pastebin.com/ER3QEcn0

**Comment by marcelveldt** [comment]
Thanks, I'll look into it. Maybe the original bg was fixed but we have to do some work in the Emby code.
Normally the kodi monitor should report the db id in the json

**Comment by agentxan** [comment]
I also was able to get the dbid and mediatype on kodi 17 without using the database by using 
```
            if KODI >= 17:
                item = xbmc.Player().getVideoInfoTag()
                kodi_id = item.getDbId()
                item_type = item.getMediaType()
```
https://github.com/agentxan/plugin.video.emby/pull/4/commits/18c16c82f482df54f6fb81104ca04c66571db993

**Comment by agentxan** [comment]
I also was able to get the dbid and mediatype on kodi 17 without using the database by using

```
            if KODI >= 17:
                item = xbmc.Player().getVideoInfoTag()
                kodi_id = item.getDbId()
                item_type = item.getMediaType()
```

agentxan@18c16c8

**Comment by marcelveldt** [comment]
nice work, that's exactly what I meant.

**Comment by marcelveldt** [comment]
Can you please update the PR so we can merge ?

**Comment by chrisnappi** [comment]
Since you mentioned you don't use Git much, if you check in to your fork it should automatically update the PR.

________________________________

**Comment by xnappo** [comment]
Looks good to me - merging and will *attempt* to remember how to release to beta.

**Comment by agentxan** [comment]
I am getting some episodes and movies that kodi 17.1 returns a -1 when using item.getDbId() from widgets. I have 5 kodi setups but it only happens on one setup. If I refresh the meta data using emby server and after that kodi updates it then gets the right id. I am going to delete the kodi database and re-sync on that one machine to see if that fixes the problem. If anyone else has this problem is might be more reliable to just get the id from MyVideos107.db directly using the file name and path like I originally was showing or another more efficient method.

**Pull request merged**
