### PR TITLE
Nest emby video nodes logically

### PR DESCRIPTION
**Pull request by delphiactual**
Video Node Cleanup

### CODE REVIEW

**Comment by delphiactual** [comment]
library://video/emby - f137a2dd21bbc1b99aa5c0f6bf02a805/f137a2dd21bbc1b99aa5c0f6bf02a805_recent.xml

becomes

library://video/emby/f137a2dd21bbc1b99aa5c0f6bf02a805/recent.xml

**Comment by angelblue05** [comment]
Thanks for this. Yes, this is a better way of doing this.

**Comment by delphiactual** [comment]
@angelblue05 adjusted the deletion task to account for new path

**Comment by angelblue05** [comment]
Thanks :)

**Comment by angelblue05** [comment]
I'll look at it once stable is out of the way

**Comment by delphiactual** [comment]
No worries, for some reason I forgot about this PR.

**Comment by angelblue05** [comment]
Thanks again for this

**Pull request merged**
