### PR TITLE
Store device id in profile

### LINKED ISSUE #142: Only last logged in user remembered when using Kodi profiles
Steps to reproduce:

1. Log in with Emby user A in "Master user" Kodi profile (the default profile that comes with Kodi)
2. Create an additional Kodi profile
3. Switch to the additional Kodi profile
4. Log in with Emby user B
5. Switch to the "Master user" profile again
6. You are logged out of Emby
7. If you log in again, the Emby user in the additional profile is logged out again

See https://emby.media/community/index.php?/topic/62041-kodi-profiles-and-emby-authentication/

### PR DESCRIPTION
**Pull request by amkay**
Fixes #142

### CODE REVIEW

**Comment by angelblue05** [comment]
I will wait to see because Luke definitely told us it's one device id per device, not per user.

**Comment by amkay** [comment]
Sure :relaxed: 

One device id per device seems reasonable.
On the other hand, I recently set up an additional user on an Android tablet and that's exactly what the Android Emby App does. I think Kodi profiles are effectively different users on one device as are Android users on one device.

**Comment by anoma** [comment]
As I understand it, if it is not `One device id per device` the current device based premiere license model will very quickly become a real issue.

i.e. `The following licenses are for single household use and carry a 15 device limit` drops effectively too 3 physical Kodi devices for an average household of 2.4 children.

Keenly following this work. Very much appreciated.

**Comment by angelblue05** [comment]
Emby for Kodi does not count towards the device limit as it is not an Emby premiere product. Just an open source project brought to you by Emby users who enjoy using Kodi.

**Comment by angelblue05** [comment]
Already resolved

**Pull request closed without merging**
