### PR TITLE
Code reduction

### PR DESCRIPTION
**Pull request by SpootDev**

### CODE REVIEW

**Comment by SpootDev** [comment]
Oh yeah, there are a few bug fixes too.

**Comment by faush01** [comment]
911 additions, 912 deletions not shown because the diff is too large. Please use a local Git client to view these changes.

**Comment by SpootDev** [comment]
No, I left the white space alone.  I nuked around 350 lines of code.  Like setting a variable from a function only to use the result only once later....instead of just using the return from the function.   Skipping varaible creates and memory copyies.  Also, alot of self.* fixes.

**Comment by SpootDev** [comment]
In addition alot of "type" fixes.  Code was using a reserved work for a variable.  Surprised Python even allowed that.

**Comment by marcelveldt** [comment]
The code looks fine to me, I think it's a good cleanup

**Comment by im85288** [comment]
Yes looks good to me too. Let's give it a day or two for Angelblue05 to comment, then merge if no objections.

**Comment by faush01** [comment]
How are you guys reviewing this, the whitespace changes are causing the online diff tool issues, is there an option to ignore whitespace changes in the GitHub review?

**Comment by angelblue05** [comment]
You guys go ahead :) Well done!

**Comment by SpootDev** [comment]
Oops, hold on......found some buggies to fix in this.  My bad.

**Comment by im85288** [comment]
Merged, any new contribution is always welcome..hopefully there is no bugs :)

**Comment by robert-chiniquy** [comment]
@faush01 Hey just btw you can ignore whitespace in github diffs by appending `?w=1` to the diff URL, like in https://github.com/MediaBrowser/plugin.video.emby/pull/27/files?w=1 — get a much nicer diff.

**Pull request merged**
