### PR TITLE
Fixed broken episode update on metadata change

### PR DESCRIPTION
**Pull request by sualfred**
See https://emby.media/community/index.php?/topic/46862-missing-ratings-on-tv-episodes-after-metadata-update/

### CODE REVIEW

**Comment by sualfred** [comment]
Okay, I missed something. It stopped working. I'll keep you update and please ignore this PR for the meantime

**Comment by marcelveldt** [comment]
No problem, we'll wait for now. Can you please update a new PR once fixed ?

**Comment by sualfred** [comment]
Yep. It just take a while, my Python skills aren't the best. I have to figure out why the unique ID won't be fetched.

**Comment by sualfred** [comment]
I've added another query to get the unique ID of the episode table, because the uniqueid table has multiple episodes with the same pathid stored. There is no episodeid to select the correct row.
If someone of you knows a better or cleaner solution, please don't hesitate to correct me :)

**Comment by sualfred** [comment]
It works, but it does not solve the root of the problem:
The uniqueid table has dublicates in the media_ID column. There is a bug in the Kodi DB creation on the inital sync progress of the episodes:
[http://imgur.com/1Tn8TxA](url)

But that's nothing I can fix, my skills are too low.

**Pull request closed without merging**
